[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.10"

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
